schema = 4
name = "CatOS Hyprland Noctalia"
description = "CatOS Hyprland desktop powered by Noctalia v5"

packages = [
  "hyprland",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "noctalia",
  "cava",
  "adw-gtk-theme",
  "breeze",
  "breeze5",
  "breeze-gtk",
  "papirus-icon-theme",
  "qt6-multimedia",
  "wtype",
  "kitty",
  "brightnessctl",
  "playerctl",
  "wireplumber",
  "qt6ct",
  "catos-bibata-cursor",
  "dconf",
  "nautilus",
  "gnome-keyring",
  "fcitx5",
  "firefox",
  "grim",
  "slurp",
  "swappy",
  "fish",
  "ttf-jetbrains-mono-nerd",
  "ttf-jetbrains-maple-mono-nf-xx-xx",
  "noto-fonts",
]

manage = [
  ".config/dconf/all.ini",
  ".config/gtk-3.0/gtk.css",
  ".config/gtk-3.0/settings.ini",
  ".config/gtk-4.0/settings.ini",
  ".config/hypr/hyprland.lua",
  ".config/kitty/kitty.conf",
  ".config/noctalia/config.toml",
  ".config/qt6ct/qt6ct.conf",
]
