hl.config({ autogenerated = false })

-- Modular configuration. Each module registers its own hl.* declarations.
-- The modules are profile seeds: they are installed once and are never
-- overwritten by catdot, so user edits survive updates of this main config.
require("modules.monitors")
require("modules.autostart")
require("modules.permissions")
require("modules.appearance")
require("modules.animations")
require("modules.layout")
require("modules.input")
require("modules.keybinds")
require("modules.rules")

-- For Noctalia Color templates
require("noctalia").apply_theme()
